# Generated by Django 4.0.5 on 2022-06-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lunch', models.CharField(default='Almoço', max_length=100)),
                ('date', models.DateField()),
                ('mainMeal', models.CharField(default='Não definido', max_length=100)),
                ('mainMealVegetarian', models.CharField(default='Não definido', max_length=100)),
                ('garrison', models.CharField(default='Não definido', max_length=100)),
                ('accompaniment', models.CharField(default='Não definido', max_length=100)),
                ('salad', models.CharField(default='Não definido', max_length=100)),
                ('dessert', models.CharField(default='Não definido', max_length=100)),
            ],
        ),
    ]
