# Generated by Django 4.0.5 on 2022-06-05 15:58

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('Almoço', 'Almoço'), ('Jantar', 'Jantar')], default='Almoço', max_length=6)),
                ('campus', models.CharField(choices=[('São Carlos', 'São Carlos'), ('Araras', 'Araras'), ('Sorocaba', 'Sorocaba'), ('Lagoa do Sino', 'Lagoa do Sino')], default='São Carlos', max_length=13)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField()),
                ('main_dish_unrestricted', models.CharField(max_length=100)),
                ('main_dish_vegetarian', models.CharField(max_length=100)),
                ('garnish', models.CharField(max_length=100)),
                ('accompaniment', models.CharField(max_length=100)),
                ('salads', models.CharField(max_length=100)),
                ('dessert', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddConstraint(
            model_name='ru',
            constraint=models.UniqueConstraint(django.db.models.expressions.F('date'), django.db.models.expressions.F('meal_type'), django.db.models.expressions.F('campus'), name='unique_date_type_campus'),
        ),
    ]
