# Generated by Django 4.0.5 on 2022-07-03 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ru', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ru',
            name='juice',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ru',
            name='main_dish_extra',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ru',
            name='accompaniment',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ru',
            name='dessert',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ru',
            name='garnish',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ru',
            name='main_dish_unrestricted',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ru',
            name='main_dish_vegetarian',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ru',
            name='salads',
            field=models.CharField(default='', max_length=100),
        ),
    ]
