# Generated by Django 4.0.5 on 2022-06-03 23:05

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('ru', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ru',
            name='lunch',
            field=models.CharField(choices=[('almoço', 'almoço'), ('jantar', 'jantar')], default='almoço', max_length=6),
        ),
        migrations.AddConstraint(
            model_name='ru',
            constraint=models.UniqueConstraint(django.db.models.expressions.F('date'), django.db.models.expressions.F('lunch'), name='unique_date_lunch'),
        ),
    ]
