# Generated by Django 4.0.5 on 2022-11-26 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ru', '0002_ru_juice_ru_main_dish_extra_alter_ru_accompaniment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
    ]
