# Generated by Django 4.0.5 on 2022-06-04 16:36

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('ru', '0002_alter_ru_lunch_ru_unique_date_lunch'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ru',
            name='unique_date_lunch',
        ),
        migrations.AddField(
            model_name='ru',
            name='campus',
            field=models.CharField(choices=[('são carlos', 'são carlos'), ('araras', 'araras'), ('sorocaba', 'sorocaba'), ('lagoa do sino', 'lagoa do sino')], default='são carlos', max_length=13),
        ),
        migrations.AddConstraint(
            model_name='ru',
            constraint=models.UniqueConstraint(django.db.models.expressions.F('date'), django.db.models.expressions.F('lunch'), django.db.models.expressions.F('campus'), name='unique_date_lunch_campus'),
        ),
    ]
