# Generated by Django 4.0.5 on 2023-05-04 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import planner_updates.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to=planner_updates.models.hash_and_path)),
                ('hash', models.CharField(editable=False, max_length=43)),
                ('key', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('runtime_version', models.CharField(max_length=64)),
                ('extra_json', models.TextField(validators=[planner_updates.models.validate_json])),
                ('channel', models.CharField(max_length=64)),
                ('platform', models.CharField(choices=[('ios', 'ios'), ('android', 'android')], max_length=7)),
                ('launch_asset', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='launch_update', to='planner_updates.asset')),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Key')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokens',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='update',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='planner_updates.update'),
        ),
    ]
