# Generated by Django 4.2.1 on 2023-07-19 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner_updates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_id', models.CharField(max_length=32)),
                ('signature', models.TextField()),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner_updates.update')),
            ],
        ),
    ]
